export const teamMembers = [
  {
    employeeId: "TH101",
    name: "Ashikur Rahman Bhuiyan",
    nickName: "Ashik",
    designation: "Founder & CEO",
    department: "Administration",
    email: "ashik@thoughthubhq.com",
    phone: "+880 1518 903860",
    bloodGroup: "O+",
    emergencyContact: "+880 1835 232410",
    avatar: "/teams/ashik.png",
    bio: "Ashik is the visionary behind our agency, blending deep technical expertise with a sharp business acumen. With over a decade of experience in full-stack architecture, he leads our core development strategies while ensuring every project meets our rigorous standard of craftsmanship.",
    linkedin: "https://linkedin.com/in/ashikurrb",
  },
  {
    employeeId: "TH102",
    name: "MD Tanim Hossain",
    nickName: "Tanim",
    designation: "CFO, Marketing Lead",
    department: "Administration",
    email: "tanim@thoughthubhq.com",
    phone: "+880 1853 431544",
    bloodGroup: "B-",
    emergencyContact: "+880 1822 000000",
    avatar: "/teams/tanim.jpg",
    bio: "Tanim drives the financial and marketing engines of the agency. His unique background in both numbers and narrative allows him to craft marketing strategies that are not only highly creative but also deeply analytical and conversion-focused.",
    linkedin: "https://linkedin.com/in/ccttanim",
  },
  {
    employeeId: "TH301",
    name: "Fardin Evan Limon",
    nickName: "Fardin Evan",
    designation: "UI/UX Designer",
    department: "Creative Design",
    email: "fardin@thoughthubhq.com",
    phone: "+880 1709-663988",
    bloodGroup: "O+",
    emergencyContact: "+880 1575-410157",
    avatar: "/teams/fardin.png",
    bio: "Fardin translates complex requirements into intuitive, breathtaking digital experiences. He obsesses over every pixel, transition, and user journey, ensuring our designs are as functional as they are beautiful.",
    linkedin: "https://linkedin.com/in/fardinevanlimon",
  },
  {
    employeeId: "TH203",
    name: "MD Ruhul Amin",
    nickName: "Ruhul Amin",
    designation: "Full Stack Developer",
    department: "Engineering",
    email: "ruhul@thoughthubhq.com",
    phone: "+880 1756-817983",
    bloodGroup: "AB+",
    emergencyContact: "+880 1756-817983",
    avatar: "/teams/ruhul.jpg",
    bio: "Ruhul specializes in building robust, scalable backend systems and seamless frontend interfaces. His code is clean, efficient, and acts as the structural backbone for some of our most complex digital platforms.",
    linkedin: "https://linkedin.com/in/md-ruhul-amin-b44528202",
  },
  {
    employeeId: "TH204",
    name: "MD Abdul Kader",
    nickName: "Jony",
    designation: "Full Stack Developer",
    department: "Engineering",
    email: "jony@thoughthubhq.com",
    phone: "+880 1788-838782",
    bloodGroup: "O-",
    emergencyContact: "+880 1823-332201",
    avatar: "/teams/jony.jpg",
    bio: "Abdul Kader is a talented full-stack developer with a passion for creating efficient and scalable solutions. His expertise spans across modern web technologies, and he is known for his ability to deliver high-quality code under tight deadlines.",
    linkedin: "https://linkedin.com/in/md-abdul-kader-b44528202",
  },
];
